version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: odisea-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: odisea_cloud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/sql:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8.4
    container_name: odisea-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: odin_user_data
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
  mysql_data:

