import { exec } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs/promises";
import path from "node:path";

const execAsync = promisify(exec);

// ─── Supported PHP versions ───────────────────────────────────────────────────

export const SUPPORTED_PHP_VERSIONS = ["8.1", "8.2", "8.3", "8.4", "8.5"] as const;
export type PHPVersion = (typeof SUPPORTED_PHP_VERSIONS)[number];

// Extensions available per version (some may vary by distro)
export const PHP_EXTENSIONS: Record<string, string[]> = {
  "8.1": [
    "common", "cli", "fpm", "mysql", "pgsql", "sqlite3", "curl", "gd",
    "imagick", "mbstring", "xml", "xmlrpc", "zip", "soap", "intl",
    "bcmath", "opcache", "redis", "memcached", "ldap", "imap", "exif",
    "readline",
  ],
  "8.2": [
    "common", "cli", "fpm", "mysql", "pgsql", "sqlite3", "curl", "gd",
    "imagick", "mbstring", "xml", "xmlrpc", "zip", "soap", "intl",
    "bcmath", "opcache", "redis", "memcached", "ldap", "imap", "exif",
    "readline",
  ],
  "8.3": [
    "common", "cli", "fpm", "mysql", "pgsql", "sqlite3", "curl", "gd",
    "imagick", "mbstring", "xml", "zip", "soap", "intl",
    "bcmath", "opcache", "redis", "memcached", "ldap", "imap", "exif",
    "readline",
  ],
  "8.4": [
    "common", "cli", "fpm", "mysql", "pgsql", "sqlite3", "curl", "gd",
    "imagick", "mbstring", "xml", "zip", "soap", "intl",
    "bcmath", "opcache", "redis", "memcached", "ldap", "imap",
    "readline",
  ],
  "8.5": [
    "common", "cli", "fpm", "mysql", "pgsql", "sqlite3", "curl", "gd",
    "mbstring", "xml", "zip", "soap", "intl",
    "bcmath", "opcache", "redis",
    "readline",
  ],
};

// ─── Check if a version is installed ─────────────────────────────────────────

export const isVersionInstalled = async (version: PHPVersion): Promise<boolean> => {
  try {
    await execAsync(`php${version} --version`);
    return true;
  } catch {
    return false;
  }
};

export const getInstalledVersions = async (): Promise<PHPVersion[]> => {
  const checks = await Promise.allSettled(
    SUPPORTED_PHP_VERSIONS.map(async (v) => {
      const ok = await isVersionInstalled(v);
      return ok ? v : null;
    })
  );

  return checks
    .filter((r): r is PromiseFulfilledResult<PHPVersion | null> => r.status === "fulfilled")
    .map((r) => r.value)
    .filter((v): v is PHPVersion => v !== null);
};

// ─── FPM pool management ──────────────────────────────────────────────────────

const poolName = (username: string) => username.replace(/[^a-z0-9_]/gi, "_").toLowerCase();

const fpmPoolPath = (version: PHPVersion, username: string): string =>
  `/etc/php/${version}/fpm/pool.d/${poolName(username)}.conf`;

const buildFpmPoolConfig = (
  username: string,
  version: PHPVersion,
  phpIni: Record<string, string> = {}
): string => {
  const safe = poolName(username);
  const socketPath = `/run/php/php${version}-fpm-${safe}.sock`;

  // Whitelisted php.ini overrides the user may set
  const ALLOWED_INI: Record<string, string> = {
    memory_limit: phpIni.memory_limit ?? "256M",
    upload_max_filesize: phpIni.upload_max_filesize ?? "100M",
    post_max_size: phpIni.post_max_size ?? "100M",
    max_execution_time: phpIni.max_execution_time ?? "60",
    max_input_time: phpIni.max_input_time ?? "60",
    "date.timezone": phpIni["date.timezone"] ?? "UTC",
  };

  const iniLines = Object.entries(ALLOWED_INI)
    .map(([k, v]) => `php_admin_value[${k}] = ${v}`)
    .join("\n");

  return `
; Auto-generated by ODISEA CLOUD — do not edit manually
[${safe}]
user = ${safe}
group = ${safe}
listen = ${socketPath}
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 500

; Security
php_admin_value[open_basedir] = /home/${safe}/:/tmp/
php_admin_flag[expose_php] = off
php_admin_flag[allow_url_fopen] = on

; User-controlled ini
${iniLines}
`.trimStart();
};

/**
 * Creates or updates the PHP-FPM pool config for a specific account.
 * Does NOT reload FPM — caller must do that after.
 */
export const writeFpmPool = async (
  username: string,
  version: PHPVersion,
  phpIni: Record<string, string> = {}
): Promise<void> => {
  const poolPath = fpmPoolPath(version, username);
  const config = buildFpmPoolConfig(username, version, phpIni);
  await fs.writeFile(poolPath, config, "utf8");
};

/**
 * Removes FPM pool config files for a user from all versions.
 */
export const removeFpmPools = async (username: string): Promise<void> => {
  await Promise.allSettled(
    SUPPORTED_PHP_VERSIONS.map((v) => fs.rm(fpmPoolPath(v, username), { force: true }))
  );
};

// ─── Nginx virtual host update ────────────────────────────────────────────────

export const updateNginxPhpSocket = async (
  username: string,
  version: PHPVersion,
  domain: string
): Promise<void> => {
  const safe = poolName(username);
  const socketPath = `/run/php/php${version}-fpm-${safe}.sock`;

  const nginxConfPath = `/etc/nginx/sites-available/${safe}`;

  // Read existing nginx config and replace fastcgi_pass socket line
  try {
    let config = await fs.readFile(nginxConfPath, "utf8");
    config = config.replace(
      /fastcgi_pass\s+unix:\/run\/php\/php[\d.]+\-fpm\-[^;]+;/g,
      `fastcgi_pass unix:${socketPath};`
    );
    await fs.writeFile(nginxConfPath, config, "utf8");
  } catch {
    // Config doesn't exist yet; generate a basic one
    const basicConfig = buildBasicNginxConfig(safe, domain, socketPath);
    await fs.writeFile(nginxConfPath, basicConfig, "utf8");

    // Enable site
    await execAsync(
      `ln -sf /etc/nginx/sites-available/${safe} /etc/nginx/sites-enabled/${safe}`
    ).catch(() => {});
  }
};

const buildBasicNginxConfig = (
  username: string,
  domain: string,
  socketPath: string
): string => `
server {
    listen 80;
    server_name ${domain} www.${domain};
    root /home/${username}/public_html;
    index index.php index.html;

    location ~ \\.php$ {
        fastcgi_pass unix:${socketPath};
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\\.ht {
        deny all;
    }
}
`.trimStart();

// ─── Reload services ──────────────────────────────────────────────────────────

export const reloadFpm = async (version: PHPVersion): Promise<void> => {
  await execAsync(`systemctl reload php${version}-fpm`);
};

export const reloadNginx = async (): Promise<void> => {
  await execAsync("nginx -s reload");
};

export const getFpmStatus = async (version: PHPVersion): Promise<"active" | "inactive" | "not_installed"> => {
  try {
    const { stdout } = await execAsync(`systemctl is-active php${version}-fpm`);
    return stdout.trim() === "active" ? "active" : "inactive";
  } catch {
    return "not_installed";
  }
};

// ─── Get installed extensions ─────────────────────────────────────────────────

export const getActiveExtensions = async (version: PHPVersion): Promise<string[]> => {
  try {
    const { stdout } = await execAsync(`php${version} -m`);
    return stdout
      .trim()
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith("["));
  } catch {
    return [];
  }
};

// ─── High-level: change PHP version for an account ───────────────────────────

export interface ChangeVersionResult {
  previousVersion: string;
  newVersion: PHPVersion;
  fpmReloaded: boolean;
  nginxReloaded: boolean;
}

export const changeAccountPhpVersion = async (
  username: string,
  newVersion: PHPVersion,
  domain: string,
  phpIni: Record<string, string> = {}
): Promise<ChangeVersionResult> => {
  const installed = await isVersionInstalled(newVersion);
  if (!installed) {
    throw new Error(
      `PHP ${newVersion} no está instalado en este servidor. Instálalo primero desde WHM → PHP Manager.`
    );
  }

  // 1. Write FPM pool for new version
  await writeFpmPool(username, newVersion, phpIni);

  // 2. Reload new FPM pool
  let fpmReloaded = false;
  try {
    await reloadFpm(newVersion);
    fpmReloaded = true;
  } catch {
    // Non-fatal: FPM might be reloaded externally
  }

  // 3. Update Nginx socket pointer
  await updateNginxPhpSocket(username, newVersion, domain);

  // 4. Reload Nginx
  let nginxReloaded = false;
  try {
    await reloadNginx();
    nginxReloaded = true;
  } catch {
    // Non-fatal on dev environments
  }

  return {
    previousVersion: "unknown",
    newVersion,
    fpmReloaded,
    nginxReloaded,
  };
};
